name: rider
description: The Fliver Rider app
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.12.9
  cupertino_icons: ^0.1.2
  dynamic_theme: ^1.0.0
  flutter_speed_dial: ^1.2.1
  geoflutterfire: ^2.0.3
  geolocator: ^4.0.3
  google_maps_flutter: ^0.5.20
  location: ^2.3.5
  permission_handler: ^3.2.2
  rxdart: ^0.22.1
  random_string: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true