name: rider
description: The Fliver Rider app
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  call_number: ^0.0.1
  cloud_firestore: ^0.12.9
  cupertino_icons: ^0.1.2
  dynamic_theme: ^1.0.0
  flutter_speed_dial: ^1.2.1
  geoflutterfire: ^2.0.3
  geolocator: ^4.0.3
  google_maps_flutter: ^0.5.20
  location: ^2.3.5
  permission_handler: ^3.2.2
  random_string: ^1.1.0
  rxdart: ^0.22.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  android: 'launcher_icon'
  image_path_android: 'assets/images/icon/icon-nobg.png'
  adaptive_icon_foreground: 'assets/images/icon/icon-nobg.png'
  adaptive_icon_background: '#1de9b6'

  ios: true
  image_path_ios: 'assets/images/icon/icon-bg.png'

flutter:
  uses-material-design: true

  assets:
     - assets/images/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
          style: italic

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Medium.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
