name: rider
description: The Fliver Rider app
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.12.9
  cupertino_icons: ^0.1.2
  dynamic_theme: ^1.0.0
  flutter_speed_dial: ^1.2.1
  geoflutterfire: ^2.0.3
  geolocator: ^5.1.4+1
  google_maps_flutter: ^0.5.21+7
  liquid_swipe: ^1.2.0
  permission_handler: ^3.2.2
  shared_preferences: ^0.5.3+5
  url_launcher: ^5.1.3

  great_circle_distance:
    git:
      url: git://github.com/fliverdev/great_circle_distance.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  android: 'launcher_icon'
  image_path_android: 'assets/icon/icon-legacy.png'
  adaptive_icon_foreground: 'assets/icon/icon-adaptive.png'
  adaptive_icon_background: '#1de9b6'

  ios: true
  image_path_ios: 'assets/icon/icon-ios.png'

flutter:
  uses-material-design: true

  assets:
     - assets/credits/
     - assets/logo/
     - assets/other/
