name: rider
description: Fliver Rider app
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dynamic_theme: ^1.0.0
  permission_handler: ^3.2.2
  location: ^2.3.5
  geolocator: ^4.0.3
  google_maps_flutter: ^0.5.20

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true